// Generated by Wrangler by running `wrangler types`

interface Env {
	MODE: string;
	CLOUDFLARE_IMAGES_ACCOUNT_ID: string;
	CLOUDFLARE_IMAGES_ACCOUNT_HASH: string;
	CLOUDFLARE_IMAGES_API_TOKEN: string;
	CLOUDFLARE_TURNSTILE_SITE_KEY: string;
	CLOUDFLARE_TURNSTILE_SECRET_KEY: string;
	MAILJET_API_KEY: string;
	MAILJET_SECRET_KEY: string;
	DB: D1Database;
}
